### ISSUE TITLE
Default DruidBeams beamMergeFn should be rollup-aware

### ISSUE THREAD

**Issue by gianm** [druid-io/tranquility#6]
The default DruidBeams beam merger is just a HashPartitionBeam, which does it based on hashCode of the event type. This can lead to sub-optimal rollup because events with the same dimension values may end up in different druid partitions, just because they have different metrics.

Instead, the default should probably partition things based on dimensions and truncated timestamp, using the user-provided DruidRollup.

The workaround for this issue is to define a custom beamMergeFn, or to override the event type's hashCode to be the same for events that should roll up together.

**Comment by nishantmonu51** [comment]
It seems this is already fixed ? 
RollupKeyPartitionBeam works by partitioning on the basis of rollup key i.e truncated timestamp and dimensions.

**Comment by pjain1** [comment]
This can cause significant difference in size of segment partitions if the data is skewed. So, does making it the default behavior OK or giving an option to achieve it make more sense ?

**Comment by pjain1** [comment]
I just realized it is a a very old issue and probably no more relevant.

**Comment by gianm** [comment]
@nishantmonu51 do you have RollupKeyPartitionBeam somewhere? I don't have one in my version of tranquility

**Comment by gianm** [comment]
@pjain1 this is still an issue, you can work around it by setting hashCode to a hash of the grouping key. I would like to fix it in tranquility core too though
